name: Print Details

on:
  push:
    branches:
      - main  # You can specify your branch here

jobs:
  print_details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
      
    - name: Read Details File
      id: read_details
      run: |
        details=$(cat details.txt)
        echo "::set-output name=details::$details"
      
    - name: Print Details
      run: echo "${{ steps.read_details.outputs.details }}"
